---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_version: 6.8.3 # set to ``current`` to build with most recent version of gradle
      gradle_commands: build # default is build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up Gradle ${{ env.gradle_version }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.gradle_version }}
      - name: Run commands
        run: gradle ${{ env.gradle_commands }}

